### ISSUE TITLE
I use it on Fedora without problem

### ISSUE THREAD

**Issue by loa-in-** [AstroSnail/apexctl#2]
Hello, should I do a PR to README file just to say it works? Never had problems

**Comment by AstroSnail** [comment]
Hi, thanks for your input.

I think it should suffice just to add the command for installing the dependencies.  
Am I correct in guessing it's `yum install hidapi-devel pkgconf`?  
Does `hidapi-devel` also fetch `hidapi`? Does `hidapi` fetch `libusb` automatically?

**Comment by AstroSnail** [comment]
I've preemptively made a commit already. If I have made any errors, please don't hesitate to tell me.

**Comment by ghost** [comment]
Building fails on Fedora after installing all dependencies, after running `make`:

```
c99 -Werror=all -Wextra -Wpedantic -Os -DENABLE_CMD_PROBE=1 -DENABLE_DATA_PRINT=0 -DHIDAPI_LONG_INCLUDE=0 $(pkgconf --cflags hidapi-libusb) -s src/apexctl.c $(pkgconf --libs hidapi-libusb) -o apexctl
Package hidapi-libusb was not found in the pkg-config search path.
Perhaps you should add the directory containing `hidapi-libusb.pc'
to the PKG_CONFIG_PATH environment variable
Package 'hidapi-libusb', required by 'virtual:world', not found
Package hidapi-libusb was not found in the pkg-config search path.
Perhaps you should add the directory containing `hidapi-libusb.pc'
to the PKG_CONFIG_PATH environment variable
Package 'hidapi-libusb', required by 'virtual:world', not found
src/apexctl.c:28:10: fatal error: hidapi.h: No such file or directory
   28 | #include <hidapi.h>
      |          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:15: apexctl] Error 1
```
EDIT: Sorry, I didn't install `hidapi-devel` as it wasn't mentioned in the readme.
