### ISSUE TITLE
apexctl tells me to "Re-run as root!"

### ISSUE THREAD

**Issue by aNDy-Squirrel** [AstroSnail/apexctl#6]
I'm on Fedora 31 using a Steelseries APEX 3 keyboard. 

Every command I try with apexctl gives me the error "Re-run as root!" while I am running the command as root. However, the commands apexctl, or apexctl -h give the help text.

Please help to fix this.

**Comment by AstroSnail** [comment]
Hi. The Apex 3 isn't currently supported by ApexCtl, and when it can't find a keyboard it supports it assumes it's running with insufficient priviledges.

I have pushed just now a commit which prints more information to explain this situation.

I don't own an Apex 3 myself so I can't test it and judge support. If you want to help, check out #3 to get an idea of what this entails.

**Comment by aNDy-Squirrel** [comment]
Hi, thanks, would be great to get this working.

lsusb gives the ID: `ID 1038:161a SteelSeries ApS SteelSeries Apex 3`

**Comment by AstroSnail** [comment]
Ok, I've pushed a commit that allows ApexCtl to recognize the Apex 3 and attempt to work with it. Just to be clear, this doesn't mean it will, only that it'll try.

**Comment by aNDy-Squirrel** [comment]
I tried a few things. 

`apexctl probe` gives a 'Segmentation fault (core dumped)'.

The fuzz script locks the keyboard up after one `apexctl probe ...` attempt, and I have to unplug and re-plug it physically. Same holds for apexctl reboot.

FYI, the APEX 3 has a 10-zone RGB illumination, so not SENWL-type.

**Comment by AstroSnail** [comment]
The 'Segmentation fault' issue turned out to be a bug in ApexCtl, thanks for finding that.

As for the keyboard locking up, sounds like it doesn't like what ApexCtl is sending it. Since I don't know how these keyboards work at all and I can't find a specification for the commands they accept, I can't help you make ApexCtl work with the Apex 3. Sorry about that.

**Comment by aNDy-Squirrel** [comment]
Thanks for the attempt. I guess you already asked the Steelseries people for information? 

I succeeded in setting a solid colour under Windows / Steelseries Engine, which is retained after un- and replugging the keyboard. For now, this is enough for my needs. Thanks again. Topic can be closed.
