### ISSUE TITLE
Disabling the RGB lightning entirely

### ISSUE THREAD

**Issue by ghost** [AstroSnail/apexctl#9]
The command `apexctl bright 1 1` (had to run as sudo) worked for my Apex Raw keyboard -- I'd appreciate if this information was added to the readme to ease the setup for new users.

**Comment by AstroSnail** [comment]
Hi, thanks for coming up and mentioning this. Just to check, does running `apexctl colors 1` (as sudo) do the same thing?

**Comment by ghost** [comment]
@AstroSnail No, running `sudo apexctl colors 1` has no effect on my keyboard while the first command `apexctl bright 1 1` disables lightning.
